### ISSUE TITLE
Light mode friendly theme

### ISSUE THREAD

**Issue by keirlawson** [knutwalker/fuzzy-select#3]
There appears to be good support for styling to suit with this crate but i wonder if it might be nice to include a theme that works well on light mode terminals as well as dark as default to save people having to brew their own? Or perhaps ship with a non-default light mode theme?

**Comment by knutwalker** [comment]
Hey, thanks for your interest :) Do you have an example theme that works on light terminals? I can certainly ship different themes as an option.
