### ISSUE TITLE
Deploy the fix over the windows

### ISSUE THREAD

**Issue by BelkacemYerfa** [knutwalker/fuzzy-select#9]
Hello @knutwalker.

Just writing, to provide the version where the windows bug is fixed on crates.io.
As i see the bug is already been fixed here #8, by @vivlim.

For anyone to make it work on his project, just download or copy paste the lib.rs code and download the dependencies:

- [Crossterm](https://crates.io/crates/crossterm)
- [Nucleo](https://crates.io/crates/nucleo)
- [unicode-segmentation](https://crates.io/crates/unicode-segmentation)
- [onlyerror](https://crates.io/crates/onlyerror)

**Comment by knutwalker** [comment]
Oh right, I should probably publish the bugfix 🙈, sorry about that

**Comment by knutwalker** [comment]
0.1.3 is released now
